### ISSUE TITLE
Please add support to be used via PSC

### ISSUE THREAD

**Issue by chipmunk2000** [GoogleCloudPlatform/iap-desktop#1028]
Would it be possible to enable the connection via PSC.
Reason, for corporate users wih corporate proxies the tunnel,cloudproxy.app url has to be enabled, however this enables the use of that url globally which is undesireable.
Trying to access it solely via PSC does not work as you dont get authorized, only option for those if wanting to use eg RDP is to set up tunnel via gcloud first and then RDP lo proxied port to connect
A split option would be acceptable ad well , eg authenticating via proxy to GCP but connecting to instanced via PSC

**Comment by jpassing** [comment]
PSC might already work if you [create DNS records by using default DNS names](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#configure-dns-default). But I guess the idea is use custom DNS names for the PSC endpoints?

I'll have to check whether it would be possible to have IAP Desktop support  [endpoint overrides like gcloud](https://cloud.google.com/sdk/gcloud/reference/topic/endpoint-override), and whether the underlying libraries support that.

But I agree that PSC support would be useful for certain types of environment.

**Comment by chipmunk2000** [comment]
even if you have googgleapis.com and accounts and oauth2  via private ips's i didnt get the authentication done, and therefore it was not working for me

**Comment by jpassing** [comment]
I ran an initial test in which I did the following:

1.  Set up a PSC endpoint with target _All Google APIs_ (`10.0.1.1`)
2.  Force the following DNS names to resolve to the PSC endpoint IP:

    ```
    accounts.google.com
    tunnel.cloudproxy.app
    oauth2.googleapis.com
    openidconnect.googleapis.com
    www.googleapis.com
    cloudresourcemanager.googleapis.com
    oslogin.googleapis.com
    compute.googleapis.com
    logging.googleapis.com
    ```

With that in place, I was able to use IAP Desktop and could observe that all traffic flowed via `10.0.1.1` (the PSC endpoint):

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/5aa689b6-b345-44f4-93de-ae893583a865)

At which step did authentication fail for you? And did you configure DNS in the same way, or is it possible that some of the DNS names were missing during your test?

**Comment by chipmunk2000** [comment]
I did manage to get it working, however , I had to do the following modifications.
Consider: 
user is a normal user in windows( no admin rights ) 
Proxy and proxysettings are  set via GPO'S and cant be altered
IAP desktop does not allow the use of file://a.pac for automatic proxyconfiguration or an option to say do not use a proxy at all 
workaround :
I had to locally install a portable nginx to serve a modified pacfile from http://127.0.0.1/a.pac, especially useful if you dont want the entire company to send all googleapis from browsers via  PSC

So the button use PSC and omit proxy would definately be worth it.

**Comment by jpassing** [comment]
Happy to hear that it worked.

Yes, I suppose adding a "Use PSC and disable proxy" option in IAP Desktop would work.

However, if you configure DNS overrides (for `compute.googleapis.com`, etc) in your internal DNS server, then these overrides not only apply to IAP Desktop, but also to other clients (incl. browsers). If you want all clients to use PSC, then it might make sense to configure the exceptions in your internal proxy's .pac file.

My preferred (and arguably a less risky) option would be to use endpoint overrides and custom DNS names (like `compute-myendpoint.p.googleapis.com`) for PSC so that you can control which clients use PSC and which don't. You could then configure `*.p.googleapis.com` as an exception in your proxy's .pac file without impacting any non-PSC clients. But I still need to investigate whether it would be possible to add support for endpoint overrides in IAP Desktop.

**Comment by jpassing** [comment]
I did a proof of concept and I'm now reasonably confident that adding support for PSC endpoint overrides should work. The idea is the following:

1. Create a PSC endpoint (for ex, `10.0.1.1`). Don't make any changes to DNS (no extra records or anything). It's also not necessary for the PSC endpoint to have a DNS name.
1. Configure IAP Desktop to use the PSC endpoint for all API connections (`*.googleapis.com`, `tunnel.cloudproxy.app`).

When you launch IAP Desktop, it first performs a browser-based sign-in. The browser-traffic would **not** go via PSC. But once that's complete, all API calls made by IAP Desktop would go via PSC.

1. Would this work in your environment?
2. Would it be neccessay for IAP Desktop to bypass the proxy for the PSC endpoint? Or would you configure that as an exception in your PAC file?
3. Would you apply the IAP Desktop configuration (PSC endpoint) manually or would you prefer to do it via group policy?

**Comment by jpassing** [comment]
If you have the opportunity, it would be great if you cloud give [this latest build of master branch](https://issuetracker.google.com/action/issues/297095653/attachments/46553219?download=true) a try. This pre-release version now lets you configure IAP Desktop to connect to Google APIs through a PSC endpoint:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/09b11f16-113c-4319-81d6-a59456b33264)

[This page](https://googlecloudplatform.github.io/iap-desktop/connect-to-google-cloud/?utm_source=iapdesktop&utm_medium=help) contains some more information about PSC support. The final release will also contain an updated ADMX policy so that you could enable PSC via an Active Directory group policy.

**Comment by jpassing** [comment]
PSC support is now available in [release 2.38](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.38.1281). If you have any feedback, please let us know (here or via the TAM).

**Comment by Lestark89** [comment]
Hello team, 

question regarding config file. We want to set specific IP into section Access >> use PSC >> Endpoint IP >> "specific IP" in files there is two config files (\Google\IAP Desktop\Config\Samples) ( Google\IAP Desktop)  i assume we need to add argument with this specific IP address to this config file correct ?
![Screenshot 2024-03-13 131853](https://github.com/GoogleCloudPlatform/iap-desktop/assets/66689939/ed170bce-8e45-4086-944f-9aeb5134497d)

**Comment by jpassing** [comment]
To let IAP Desktop connect to Google APIs thru Private Service Connect, look up the [IP address or FQDN of your PSC endpoint](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#console_3) and enter it into the **Endpoint** field. After you relaunch IAP Desktop, all Google API calls will go thru that PSC endpoint.

You don't need to make any changes in any of the config files.
