### ISSUE TITLE
Change resolution settings

### ISSUE THREAD

**Issue by mark-chia** [GoogleCloudPlatform/iap-desktop#1100]
Just discovered this after having issues with Remote Desktop Connection and works great!

Minor issue is that the resolution of my RDP session is quite blurry. I have tried the three different Desktop Size options (client size, screen size, auto adjust) and doesn't make a difference. When I access the display settings within the RDP, it says 'The display settings can't be changed from a remote session.' I am connecting to a Windows Server 2022 Datacenter and my local screen is 3000x2000, 260 PPI.

**Comment by jpassing** [comment]
Thanks for reporting this. 

I see that this can be an issue when you use a high-DPI screen. IAP Desktop is currently not DPI-aware, which means IAP Desktop paints at the default DPI rate and Windows then scales it up to match your configured DPI setting. That can cause some blurriness in the app itself (menu, controls, etc), and that blurriness can extend to the remote desktop.

I assume that the proper fix would be to make IAP Desktop fully DPI-aware. That's something I'd like to do because high-DPI screens are increasingly common. But there are still a few other items that are currently higher on the roadmap, so it might take a bit.

And yes, the remote desktop screen resolution is [controlled by the client](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt703457(v=vs.85)) (IAP Desktop, in this case), that's why you couldn't change it server-side.

**Comment by mark-chia** [comment]
Thanks for your response and the explanation!
