### ISSUE TITLE
Customers RDP keeps kicking him off - unknown error code 3336 

### ISSUE THREAD

**Issue by LukeWatsonMG** [GoogleCloudPlatform/iap-desktop#111]
Expected behavior:
* Step 1
* Step 2
* ...

Observed behavior:
* Step 1
* Step 2
* ...

Installed version: 2.0.86.0
.NET Version: 4.0.30319.42000
OS Version: Microsoft Windows NT 6.2.9200.0

**Comment by jpassing** [comment]
Do you get this error for a specific VM or any VM you connect to?

RDP error `3336` is not documented, so I am not sure what it means. But error `3335` is `The account is locked out` -- so there's a chance that `3336` is also user-related. Could you give it a try with a different/new user and see how that works?

Are you currently using a local user or a domain user to sign in?

**Comment by LukeWatsonMG** [comment]
We only have one VM in our GCP at the minute so i can't say if it affects more than just this instance. 

Using Local user to sign in, the VM clock is also an hour out (working to address this this evening)

**Comment by itspage** [comment]
We're seeing the same thing here when we minimise the IAP desktop app window (not within RDP when in full screen - as we are aware of that issue).

![thumbnail_image003](https://user-images.githubusercontent.com/5963447/81836120-f5a38e80-953a-11ea-8e09-a98549e7f1b9.jpg)

**Comment by LukeWatsonMG** [comment]
> We're seeing the same thing here when we minimise the IAP desktop app window (not within RDP when in full screen - as we are aware of that issue).
> 
> ![thumbnail_image003](https://user-images.githubusercontent.com/5963447/81836120-f5a38e80-953a-11ea-8e09-a98549e7f1b9.jpg)

**Comment by LukeWatsonMG** [comment]
Closed by mistake, apologies ( just like my IAP Session : I

**Comment by LukeWatsonMG** [comment]
Debugged last night and think this is related to session manager

**Comment by jpassing** [comment]
I was able to reproduce the issue and [made a few changes](https://github.com/GoogleCloudPlatform/iap-desktop/pull/113). 

First, I made the error message more verbose so that it should now include further information about what issue the RDP control ran into.

Second, I reduced the number of cases where the RDP control reconnects because the window size changed. Especially minimizing and restoring the window caused unnecessary reconnects which just made everything more brittle.

[Here's a build of the latest master branch](https://storage.googleapis.com/jpassing-public/IapDesktop-2.1.114.0.msi). It would be great if you could give it a try and see if that fixes the issue for you, or whether you at least get a more specific error message.

**Comment by jpassing** [comment]
I just release [2.1.114](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.1.114), which includes the fixes mentioned in my previous comment.

Please re-open this bug if that new release does not fix the issue for you.
