### ISSUE TITLE
Session disconnections 

### ISSUE THREAD

**Issue by thapoffice** [GoogleCloudPlatform/iap-desktop#115]
Observed behavior:
The Remote desktop connects fine but when ever I try to resize the window or change to full screen the connection drops and Reconnecting pop up window appears.
* ...

Expected the connection should not drop every time there is a window resize be it full screen or docked.

Installed version: 2.1.114.0
.NET Version: 4.0.30319.42000
OS Version: Microsoft Windows NT 6.2.9200.0

**Comment by jpassing** [comment]
Unfortunately, the RDP control does not support resizing [without reconnecting](https://docs.microsoft.com/en-us/windows/win32/termserv/imsrdpclient8-reconnect). Therefore, the expected behavior is:

1. Resize window
1. Reconnect dialog appears for ~2 seconds
1. Reconnected with new screen size

Is that what you are seeing? Or does the reconnect (2) fail?
