### ISSUE TITLE
Unable To Add Project I Don't Own

### ISSUE THREAD

**Issue by shpml** [GoogleCloudPlatform/iap-desktop#1167]
I am unable to add a project I don't own. I have been given access to a couple of client VMs via IAP.  I have all the correct access as I can connect to the VMs using the gcloud cli on a MAC but I can't use the windows `iap-desktop` client as I can't add the project that VMs reside in as it's owned by the client.

**Comment by jpassing** [comment]
Adding a project to IAP Desktop [requires _Compute Viewer_ (or equivalent) access](https://googlecloudplatform.github.io/iap-desktop/install/#access-your-projects) to the project. This role is necessary so that IAP Desktop can enumerate and show the list of VMs in Project Explorer. Note that it doesn't matter who owns the project or which GCP organization it belongs to.

If the project doesn't show up in the _Add project_ dialog, then you're probably missing that role. If you can add the project, but it shows up empty, then you might be violating a VPC service control perimeter configuration.

Note that if you only have _IAP-Secured Tunnel User_ access, you can still [connect to Windows VMs by URL](https://googlecloudplatform.github.io/iap-desktop/connect-by-url/) -- but that's obviously less comfortable.

**Comment by shpml** [comment]
I have the the role `roles/compute.instanceAdmin.v1`. I can administer the instances through the gcloud tool fine as I know the name of the project I'm working with but with the `iap-desktop` I can't add the project I need to work with. 

I assume it's because I don't have any permissions to list or view projects and the `iap-desktop` looks like it does a search. Even if I type the full name of the project into the add projects search bar I can't add the project. I would be good to be able to directly add the project by name. 

I have the following permissions:
```
gcloud projects get-iam-policy <GCP_PROJECT>  \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:<USER_EMAIL>"
ROLE
projects/GCP_PROJECT/roles/custom_role
roles/compute.instanceAdmin.v1
roles/iam.serviceAccountUser
```

The permissions on custom role are:
```
    "iap.tunnelInstances.accessViaIAP",
    "compute.instances.get",
    "compute.instances.list",
    "compute.projects.get",
    "compute.instances.setMetadata",
    "compute.projects.setCommonInstanceMetadata",
    "compute.globalOperations.get",
    "iam.serviceAccounts.actAs"
```

**Comment by jpassing** [comment]
Thanks for providing the list of roles. The _Compute Instance Admin (v1)_ role includes the `resourcemanager.projects.get` permission, and that's [all you need for the project to show up in search results](https://cloud.google.com/resource-manager/reference/rest/v1/projects/list#:~:text=If%20no%20filter%20is%20specified%2C%20the%20call%20will%20return%20projects%20for%20which%20the%20user%20has%20the%20resourcemanager.projects.get%20permission.). However, what I figure might be happening here is that the organization that contains the project has a [`constraints/resourcemanager.accessBoundaries` constraint](https://cloud.google.com/resource-manager/docs/access-control-org#restricting_visibility) that causes the project to be hidden from search results. Do you think that's possible?

As a workaround, you can "force-add" a project by creating a registry key manually:

1. Open a command prompt and run `reg add HKCU\SOFTWARE\Google\IapDesktop\1.0\Inventory\PROJECT_ID` (where `PROJECT_ID` is the project ID)
2. Refresh Project Explorer or relaunch the app

**Comment by shpml** [comment]
The role `roles/compute.instanceAdmin.v1` has the below condition attached. And if it provides `resourcemanager.projects.get` then I guess that condition is applied there also. 

```
resource.name.startsWith("projects/GCP_PROJECT/zones/australia-southeast1-a/instances/INSTANCE_PREFIX-")
|| resource.name.startsWith("projects/GCP_PROJECT/zones/australia-southeast1-b/instances/INSTANCE_PREFIX-")
...
```

The `reg add` work around worked nicely thanks.
