### ISSUE TITLE
Feature request: specify local port number for SSH tunnels.

### ISSUE THREAD

**Issue by greyfairer** [GoogleCloudPlatform/iap-desktop#1192]
Using  `Forward local port`, you can specify the remote port for an SSH tunnel, but you can't customize the local port.

Typically, I have all the SQL connections configured in my DBeaver SQL client, and DBeaver is the first thing I start in the morning.
I use IAP desktop to start the tunnel when I need access to a Google Cloud SQL server, and then connect my DBeaver to the configured connection string.

Luckily, the local port is deterministic, so I can hard-code it in my SQL connection string for Cloud SQL. But I can't predict the port number before I connect for the first time.

It could be useful to allow to specify the local port, too.

For now, I still use the `gcloud compute` CLI to setup those SSH tunnels because I can specify the local port number, and that's more convenient to setup and document it for my colleagues.

**Comment by jpassing** [comment]
This seems like a useful feature to add.

One option would be to extend the _Forward local port_ dialog to let you (optionally) specify a client port number. There's obviously a risk that the port is already in use, in which case the command would fail:


![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/837a38aa-364a-4aad-a261-7bd768ea1866)

Another option would be to extend the [client application configuration mechanism](https://googlecloudplatform.github.io/iap-desktop/client-application-configuration/): Currently, you have to specify a client application to launch, but we could remove that requirement so that you could register something like the following:

```
{
  "version": 1,
  "name": "SQL Server port-forwarding (41433)",
  "condition": "isInstance()",
  "remotePort": "1433",
  "localPort": "41433"
}
```

You'd then see a menu item **Connect client application > SQL Server port-forwarding (41433)** in the context menu, and it would always create a port forwarding on port `41433`.

The two options aren't mutually exclusive, but if you have any preferences/thoughts, let me know.

**Comment by greyfairer** [comment]
@jpassing the second option is actually even better. 
That way we don't even have to remember the ports, they are in the .iapc file.

**Comment by jpassing** [comment]
I missed to update this issue earlier -- as of version 2.38, you now can let IAP Desktop open a tunnel to SQL Server _without_ having it launch SMSS:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/e6ad7e3d-72f3-42f9-8303-99fb3c037a4b)

You should be able to use that and connect to the tunnel from within DBeaver.

For applications other than SQL Server, you can [create custom client configuration file as documented here](https://googlecloudplatform.github.io/iap-desktop/client-application-configuration/).

I hope this works in your scenario, otherwise please let me know.
