### ISSUE TITLE
Authentication using Microsoft Account

### ISSUE THREAD

**Issue by aymanelbacha** [GoogleCloudPlatform/iap-desktop#1230]
We'd like to know if we can authenticate without signing up for a gmail account using the user corporate email via identity platform choosing Microsoft as the provider when authenticating to IAP desktop to connect to an SQL instance vi SSMS

**Comment by jpassing** [comment]
When signing in to IAP Desktop, use the same user account that you'd normally use to sign in to the Cloud Console, `gcloud`, or another Google service. Don't create an extra Gmail user just for the purpose of using IAP Desktop.

If you've configured Cloud Identity or Workspace [so that it uses Microsoft Entra ID as single sign-on provider](https://cloud.google.com/architecture/identity/federating-gcp-with-azure-ad-configuring-provisioning-and-single-sign-on), then that should work just fine.

Does that answer your question?

**Comment by jpassing** [comment]
I assume that this is resolved? If not, please feel free to reopen the issue.
