### ISSUE TITLE
Cannot SSH to a compute engine VM with IAP-Desktop

### ISSUE THREAD

**Issue by nirforer** [GoogleCloudPlatform/iap-desktop#1278]
Hi, we're trying to SSH into a VM with IAP desktop, this VM is configured the same as other VMs in terms of OS Login etc. One specific user cannot SSH to one specific VM. The same user is able to SSH to other VMs and other users are able to SSH to the VM that fails for this user. The user is able to SSH to the VM with Putty.
Attaching the debug log , the error indicates:
[iap_debug.log](https://github.com/GoogleCloudPlatform/iap-desktop/files/14181118/iap_debug.log)

Google.Solutions.IapDesktop.Extensions.Session.ToolWindows.Ssh.MetadataKeyAuthenticationFailedException: Authentication failed. Verify that the Compute Engine guest environment is installed on the VM and that the agent is running. ---> Google.Solutions.Ssh.Native.SshNativeException: Username/PublicKey combination invalid

We're not sure how to tackle this, we've tried the SSH troubleshooting steps but this didn't solve the issue

Attaching the full debug log

Thanks!

**Comment by jpassing** [comment]
The attached log file indicates that...

* the VM uses metadata-based keys (as opposed to OS Login)
* there is an existing `ecdsa-sha2-nistp384` key for the respective user in project or instance metadata

... but authenticating using that key failed.

It would be useful to take a look at the VM's SSHD logs (`/var/log/secure` or `auth.log`, depending on your guest OS). The log should indicate whether authentication failed because of a public key mismatch or because of some other reason.


If it's a public key mismatch, you can let the affected user try the following:

1. Go to Tools > Options > SSH 
2. Switch to a different key type (such as NISTP-521). That causes IAP Desktop to create and upload a new key.
3. Try connecting again.

Alternatively, you can use the **Authorized SSH keys** window to find and delete the user's existing public key. This causes IAP Desktop to re-upload its key the next time the user connects.

If the error is account-related, try changing the user's connection settings so that it uses the same username as putty:

1. Right-click the VM in the Project Explorer window and select **Connection settings**. 
2. Set **Username** to the username they use in putty. This ensures that IAP Desktop uses the same Linux user as putty.

**Comment by jpassing** [comment]
As I haven't heard back, I assume that this is resolved? If not, please re-open the issue.
