### ISSUE TITLE
Desktop Size option seems to be missing in the latest version of IAP

### ISSUE THREAD

**Issue by coreyman** [GoogleCloudPlatform/iap-desktop#1461]
This is an issue for us now. We have users on tiny screens and are needing to use ClientSize instead of AutoAdjust so that they get the scrollbars but the Desktop Size option seems to be missing in the latest version of IAP. Was this intentional? Can we get the option back?

https://github.com/GoogleCloudPlatform/iap-desktop/issues/443

**Comment by jpassing** [comment]
Yes, I removed the `ClientSize` option (in [2.40](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.40.1418), iirc) as part of the implementation to allow faster RDP full-screen switching, primarily because this option didn't seem to be used much.

Would you prefer bring back the `ClientSize` option or adding a zoom option (so that you could go to 75%, for example).

**Comment by coreyman** [comment]
Our users on small screens prefer the ClientSize option. If they used zoom they wouldn't be able to see text as easily. 
Since it's just an option maybe there can be a warning when enabling or an automatic disable of the option when in full-screen for the faster RDP full-screen switching?

**Comment by jpassing** [comment]
Before I implement the wrong thing, could you confirm that it's indeed the `ClientSize` option that you're looking for? This option used to have the following effect: The remote desktop was sized to fit the size of the IAP Desktop window and kept constant. Resizing the  IAP Desktop window did not affect the remote desktop size.

Or are you looking for the old `ScreenSize` option which set the remote desktop size to match your local screen resololution? In windowed (i.e., non-fullscreen) mode, IAP Desktop then showed scrollbars. When switching to full-screen, the remote desktop size was kept unchanged because it already matched the local screen resolution.

For devices with very smalls creens, I can see the benefit of  `ScreenSize` -- but I'm not entirely sure how `ClientSize` would be any better than the current default behavior of auto-adjusting the size.

**Comment by coreyman** [comment]
I think either one would work for our users.

**Comment by bmd9526git** [comment]
I would also find it useful if I could change the display size

**Comment by jpassing** [comment]
[Here's a (signed) installer package of the latest development build, `2.43.1616`](https://issuetracker.google.com/action/issues/373737414/attachments/60108050?download=true). This build adds a new connection setting, **Display resolution**:

![image](https://github.com/user-attachments/assets/a2c90fe0-835d-440a-9e7b-5de213c6278f)


If you set this to **Same as this computer**, IAP Desktop sets the remote desktop size to match your current screen's size, and keeps the size constant when you resize the window or enter/leave full-screen. This is equivalent to the old `ScreenSize` setting.

If you have the time, it would be great if you could give that a try and let me know if it works as expected.

**Comment by jpassing** [comment]
The feature is now available in [release 2.43](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.43.1627).
