### ISSUE TITLE
First attempt of credentials not working.

### ISSUE THREAD

**Issue by ronaldocondebakkt** [GoogleCloudPlatform/iap-desktop#1537]
When trying to RDP a Windows machine, it does not connect to and report as the message

"The server's authentication policy does not allow connection requests using saved credentials. Please enter new credentials."

I'm not using saved credentials, and on second trial the connection happens.

![saved_credentials](https://github.com/user-attachments/assets/e778c5cf-cdb9-46cb-8337-6b182ebd12f9)

**Comment by jpassing** [comment]
This error message indicates that the VM you're connecting to [has the _Always prompt for password upon connection_ group policy enabled](https://googlecloudplatform.github.io/iap-desktop/troubleshooting-rdp/#your-credentials-did-not-work-when-using-saved-credentials).

When you connect to a VM using default settings, IAP Desktop shows a credential prompt with a "remember me" checkbox, and then passes these credentials to the RDP connection. 

For VMs that have this particular group policy enabled, this default behavior doesn't work well because to the server, it looks like you are using saved credentials (even though you might not be), and as a result, you're prompted for credentials a second time.  For these VMs, it's therefore best to set  [Automatic logon](https://googlecloudplatform.github.io/iap-desktop/toolwindow-connection-settings/#remote-desktop-security-settings) to _Disabled_ in the connection settings. This setting was recently introduced in version 2.43 and suppresses the default credential prompting behavior of UAP Desktop.

You can configure the _Automatic logon_ setting for a specific VMs, [or for an entire project](https://googlecloudplatform.github.io/iap-desktop/toolwindow-connection-settings/#remote-desktop-security-settings:~:text=You%20can%20override%20inherited%20settings%20at%20lower%20levels.%20Whenever%20a%20setting%20deviates%20from%20the%20(inherited)%20default%2C%20its%20value%20is%20shown%20in%20bold%20typeface.).

For more context, see #1501.

**Comment by jpassing** [comment]
Did changing the _Automatic logon_ setting to _Disabled_ fix the problem? If not, please reopen the issue.
