### ISSUE TITLE
Add feature not to list all VM's in a project | TCP tunneling

### ISSUE THREAD

**Issue by dpskanpur** [GoogleCloudPlatform/iap-desktop#156]
Can this be done, that when I give a user or group permission to access certain VM, he is not seeing the other list of VM's in the project? I don't want to create new project and get this done.
Also, I can't remove, compute. list permission as this is must be needed to run the API. This shud apply to both User and group.

**Comment by gchampion** [comment]
bump

**Comment by JeSappelleRoot** [comment]
+1
This feature could be usefull

**Comment by jpassing** [comment]
Thanks for the suggestion, I'll look into this.

**Comment by jpassing** [comment]
To list VMs in the project explorer window, you need the `compute.instances.list` permission on a project. The issue here is that once you have been granted this permission, you can see all VMs of that project. It's currently not possible to further restrict the permission so that a user can only see a subset of VMs. 

If you want to give users RDP access to only particular machines, and do not want them to see/browse the respective projects at all, using the [browser integration feature](https://github.com/GoogleCloudPlatform/iap-desktop/wiki/Browser-Integration) might be an option to consider. If you launch IAP Desktop using an `iap-rdp:///` URL, it will immediately connect to that machine and the only role required is `IAP-secured tunnel user` for that particular VM.

Maybe you can share some more information about your use cases, that would be helpful.

**Comment by JeSappelleRoot** [comment]
Yep, this could solve our use cases 
https://github.com/GoogleCloudPlatform/iap-desktop/wiki/Browser-Integration

Thanks @jpassing for your quick answer

**Comment by gchampion** [comment]
@jpassing Use case is "jump servers" devs use for access , they only need to sign onto those boxes. Somewhat a security vulnerability for the to see all boxes listed.

**Comment by taoszhanna** [comment]
I think this is not a desired feature. If the other servers shouldn’t be visible, then they shouldn’t be in that GCP project. They could be in the same network, but not the same project. This is a textbook use case for using Shared VPC constructs properly to prevent the scenario described

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dpskanpur** [comment]
well, this depends on the use case, @jpassing I agree with browser integration but I'm not sure if that works with the group too. and seems because we cannot fine grade the compute. list permission more programmatically this as best we can have. I made a script to RDP instance via -- tunnel and turn into exe. Simple and given to the user. works charm.

@taoszhanna  I have a scenario wherein I can't call the same API for two projects, different projects have different API. But yes the different project is what this is meant for.

**Comment by jpassing** [comment]
It's a bit of a gray area... on the one hand, I agree with @taoszhanna that requiring per-VM permissions can be an indicator that using separate projects and a shared VPC would be a better approach. But there are some cases where it makes sense to grant users access to specific VMs only. That's why we added the browser-integration feature.

Currently, if you use the browser-integration feature to connect to a VM, that VM does not show up in the project explorer. As a consequence, you cannot change the connection settings and IAP Desktop immediately forgets about the VM once you close the connection.

I figure it might be useful to have IAP Desktop track and remember those "ephemeral" VMs in project explorer so that you can change settings and find them again the next time you start the app. Do you think that would help?

**Comment by JeSappelleRoot** [comment]
Hi @jpassing 
I know that it's an old open case 
Do you have any update/functionality about `compute.instances.list` wild permissions ? 
I already tested the browser integration but this was not the desired functionality

**Comment by jpassing** [comment]
I did some more research, but the situation has not really changed: Listing VM instances is an all-or-nothing thing -- if you have `compute.instances.list`, you can see all instances and without the permission you cannot see any. IAM conditions do not really help either as they cannot be used for "filtering" the result set.

Narrowing down the list of VMs to specific zones would be possible -- but I guess that's no too helpful either.

Regarding browser integration: If you enable this feature, you can also create Windows URL shortcuts to `iap-rdp:///` URLs (as a sort-of replacement for .rdp files). If it's always the same few VMs that you connect to, maybe that's another option to consider?

**Comment by JeSappelleRoot** [comment]
Hey @jpassing 
Thanks for your reply.
We are trying to figure out with permissions but looks like we are back to square one
Thanks for your help on this, we are still enjoying Desktop IAP everyday !

**Comment by jpassing** [comment]
Given the constraints imposed by the Compute Engine API, I unfortunately don't see any way to fix this issue in IAP Desktop. So I'm closing the issue for now.
