### ISSUE TITLE
Newer Versions of IAP Desktop Not Detecting WIndows 10 Version Correctly?

### ISSUE THREAD

**Issue by RCJazzBass** [GoogleCloudPlatform/iap-desktop#1580]
Hello and a BIG thanks for working on this project. It has been invaluable in my daily workflow.

I'm currently on 2.41.1463 and I cannot upgrade to newer versions because the install thinks I'm running a now unsupported version of Windows 10.

Under About > Windows specifications, I have this:
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎1/‎26/‎2024
OS build	19045.5131
Experience	Windows Feature Experience Pack 1000.19060.1000.0

It seems that the newer versions should install since 22H2 is a later version than the required 1607 version. (ref: https://en.wikipedia.org/wiki/Windows_10_version_history)

Am I wrong or is this a bug?

Thank you very much in advance!
RC

**Comment by jpassing** [comment]
>It has been invaluable in my daily workflow.

I'm happy to hear that :) 


I guess the error message that you're seeing is 

> This version of IAP Desktop requires Windows 10 (1607), Windows Server 2016, or higher.

when trying to install the MSI package. Is that correct? This is indeed unusual because [Win10 22H2 should work fine](https://github.com/GoogleCloudPlatform/iap-desktop/blob/9dad0a4579e5bad2f3e27282d5ff48e685c1631b/sources/installer/Product.wxs#L80). 

The installer checks the registry value `CurrentBuildNumber` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion` to determine the Windows version that you're running. I suspect that for some reason, this value might be incorrect on your machine, or contain a value below `14393`.

There are two ways you could work around this issue:

1. If you have admin privileges, you could temporarily modify the registry value:

   1. Change `CurrentBuildNumber` to `14393` (or above)
   3. Run the installer
   4. Change `CurrentBuildNumber`  back to its previous value

   I typically wouldn't recommend changing this value manually, but if you change it back immediately the risk should be small.

2. Alternatively, you can [perform an administrative install](https://googlecloudplatform.github.io/iap-desktop/troubleshooting/#c-performing-an-administrative-installation), which essentially just unpacks the MSI package.

**Comment by RCJazzBass** [comment]
Thank you so much for your quick response! Yes, that is the message I'm receiving.

I took a look at the registry setting you mentioned and it is not below 14393; it is 19045

![image](https://github.com/user-attachments/assets/78c82e02-2b3d-4d83-99fd-89d624a28e9c)

I'll see about running the administrative install and see if that works for me.

Thank you!
RC

**Comment by jpassing** [comment]
> I took a look at the registry setting you mentioned and it is not below 14393; it is 19045

Interesting, thanks for checking that.

Would it be possible to run the installer again and enable logging? That would allow me to take a closer look at which property is causing the launch condition to fail.

1. Open a command prompt
2. Launch the installer with logging enabled:
    ```
    msiexec /l* install.log /i IapDesktop.msi
    ```
    (in case you're using PowerShell, make sure to remove any `.\` prefix; `msiexec` doesn't like that.

Instead of sharing the log file here, I'd suggest to share it privately by sending it to `iap-desktop@google.com`.

**Comment by RCJazzBass** [comment]
OK. Got the log and sent to the email address provided.

Thanks again!

**Comment by jpassing** [comment]
Thank you for sharing the log file. The important cues are:

```
Action start 6:19:09: ExecuteAction.
MSI (s) (D4:B0) [06:19:16:649]: Ignoring disallowed property WINDOWS_CURRENTBUILDNUMBER
```

and

```
Property(S): RestrictedUserControl = 1
```

I'm not sure about the exact circumstances that causes `RestrictedUserControl ` to be set in your case, but the result is that `WINDOWS_CURRENTBUILDNUMBER` is ignored, and that causes the launch condition to fail.

I prepared a [fix](https://github.com/GoogleCloudPlatform/iap-desktop/issues/1580) that I think should solve the issue and you can download a signed [installer package here](https://issuetracker.google.com/action/issues/382142002/attachments/61286615?download=true) that contains the fix. Could you give this one a try and let me know if the install works now?

**Comment by RCJazzBass** [comment]
Great hunting! Thank you so much for your help with this.

I downloaded the new installer package and it works without issue! Installed without the warning so it appears to be good to go.

Thanks again!

**Comment by jpassing** [comment]
Great! Thanks for reporting this issue and helping resolve it.
