### ISSUE TITLE
Add support for port forwarding with SSH

### ISSUE THREAD

**Issue by Pienskoi** [GoogleCloudPlatform/iap-desktop#1593]
I am using recommended approach by Google to connect to a Cloud SQL instance from outside its VPC - https://cloud.google.com/sql/docs/mysql/connect-to-instance-from-outside-vpc#iap. It consists of intermediary VM with Cloud Auth Proxy installed. Connection is set up by opening SSH tunnel with IAP and port forwarding DB ports on VM to local ports.

Please add support for port forwarding when establishing SSH connections to VMs through IAP. This would replicate functionality currently available through gcloud CLI:
```bash
gcloud compute ssh VM_NAME \
--tunnel-through-iap \
--ssh-flag="-L 5432:localhost:5432"
```

There was a similar issue #936 but it was resolved by adding support for creating IAP tunnels to different ports and changing architecture to remove SSH tunnel.

**Comment by jpassing** [comment]
Instead of using SSH port forwarding, you can also use IAP-TCP to connect to the Cloud SQL proxy directly:

1. On the intermediary VM, launch the Cloud SQL proxy and let it bind to the VM's private IP (`10.0.0.2`  in my case) instead of `127.0.0.1`:

        ./cloud-sql-proxy--private-ip -a 10.0.0.2 my-project:asia-southeast1:my-sqlinstance

2. Create a firewall rule to allow IAP-TCP connections to port `5432`:

        gcloud compute firewall-rules create allow-psql-ingress-from-iap \
            --direction=INGRESS \
            --action=allow \
            --rules=tcp:5432 \
            --source-ranges=35.235.240.0/20

3.  In IAP Desktop, right-click the VM and select **Tunnel to > Postgre SQL**.
4. If you go to **View > Active IAP Tunnels**, you can see that there's an open tunnel. 

    ![image](https://github.com/user-attachments/assets/3e461838-2f38-4323-a3cb-10717ccd3157)

    In my case, the tunnel is listening on port 18344, yours might be different. The port should be the same every time you create a tunnel to the same VM though.

5.  Use `psql` and connect to `127.0.0.1:18344`:

        psql -U postgres -h 127.0.0.1 -p 18344



One advantage of using SSH port-forwarding (as described in the product docs) as opposed to using IAP-TCP directly (as described above) is that the Cloud SQL proxy only needs to bind to `127.0.0.1`. Depending on how your VPC's firewall rules are set up, letting the proxy bind to the instance's private IP might allow other VMs in that VPC to connect to it too. So if you follow the approach above, it might be best to ensure that _only_ IAP-TCP (`35.235.240.0/20` is allowed to connect to port `5432`).

**Comment by Pienskoi** [comment]
Thanks for the detailed solution and explanation! I'll give it a try.

I'll close this issue.
