### ISSUE TITLE
RDP session disconnects instantly after switching to Full Screen

### ISSUE THREAD

**Issue by pdinno** [GoogleCloudPlatform/iap-desktop#245]
The IAP-Desktop application connects to the required Windows GCE instance through RDP(over the IAP tunnel) normally.
There is no interruption whatsoever while working on the standard window size.

As soon as the View is switched to Full Screen, the RDP session disconnects instantly -
 
![image](https://user-images.githubusercontent.com/53219045/91720089-1eb46180-ebb4-11ea-8f1d-916dc5f072e3.png)

I have observed it for **each** time that I have tried to switch.

Please assist with the same.

**Comment by jpassing** [comment]
Does the reconnect succeed though, and is the screen resolution correct after the reconnect? Or does the reconnect fail?

Some context: Historically, RDP always required a reconnect to resize the window. Newer versions of Windows/RDP support resizing without reconnecting, but that feature is not available in all situations, for example it does not work during logon. As of version 2.4, IAP Desktop always attempts to resize _without_ reconnecting -- if that fails for whatever reason, it falls back to resizing _with_ reconnecting.

If your client or server is running Windows 8.1/2012 R2 or lower, then I'd always expect reconnects to happen. For newer versions, it _usually_ should work without reconnecting.

**Comment by pdinno** [comment]
Thank you for providing the required context.

The re-connect attempt succeeds and the screen resolution is correct afterwards. 
Additionally, there are no disconnects even after switching back to standard view.

Ah, ok.
I'm currently running Windows Server 2016 though.

**Comment by jpassing** [comment]
I just checked [the code](https://github.com/GoogleCloudPlatform/iap-desktop/blob/336dd9b17adc76d06d71ac05b4004cb6248f1156/sources/Google.Solutions.IapDesktop.Application/Views/RemoteDesktop/RemoteDesktopPane.cs#L280) again -- indeed, entering full screen always triggers a reconnect. In theory, that should not be necessary but there seems to be some quirk in the RDP control that causes things to break if you try to go full-screen without a reconnect. In contrast, leaving full screen or resizing the window should work without a reconnect on Windows 10/2016+ -- so what you're seeing is expected behavior.

I wish I could improve the UX here, but I am constrained to what the RDP control supports -- so I suspect there is not much room for improvement here...

**Comment by pdinno** [comment]
That is duly noted.
Thanks for providing the required support!
