### ISSUE TITLE
Allow minimizing full-screen view

### ISSUE THREAD

**Issue by leqnam** [GoogleCloudPlatform/iap-desktop#500]
Verry appreciate on the project, 
When entering to full screen, it disconnected and have to wait a little bit to re-connect. Also no option to minimize the full screen.

![image](https://user-images.githubusercontent.com/6275689/119132321-c33d4300-ba64-11eb-8e72-39c22e9f1c2e.png)

**Comment by jpassing** [comment]
RDP is a bit peculiar when it comes to changing the window size/screen resolution. In many cases, it's possible to do so without reconnecting, but there are some scenarios (like entering full-screen mode) where a reconnect [is necessary](https://github.com/GoogleCloudPlatform/iap-desktop/blob/ad989f680d30d6024b38b7c3ee79de3b5cb4b478/sources/Google.Solutions.IapDesktop.Extensions.Shell/Views/RemoteDesktop/RemoteDesktopPane.cs#L363). I agree that the reconnect is a bit annoying, but I don't think it can be avoided.

A previous version of IAP Desktop showed the Minimize button, but it only minimized the current (full-screen) RDP window while the main window remained visible. That behavior was odd and is the reason why the button is hidden now.

I suppose we could change the app so that the Minimize button minimizes the full-screen window *and* the main window.
