### ISSUE TITLE
Bump TLS version to 1.3

### ISSUE THREAD

**Issue by vit4ever** [GoogleCloudPlatform/iap-desktop#544]
It looks like iap-desktop just support TLS 1.2 according to https://github.com/GoogleCloudPlatform/iap-desktop/blob/master/sources/Google.Solutions.IapDesktop/Program.cs
My network logs show the same.
In contrast using IAP via gcloud uses TLS 1.3, also all google cloud services use TLS 1.3 afaik.
Since TLS 1.3 has been around for a while and is supported by each major OS  could you consider to bump the version to TLS 1.3 and maybe also remove support for TLS 1.1  ?

**Comment by jpassing** [comment]
Thanks for bringing this up. I did a few experiments and unfortunately, things seem to be a bit tricky: 

* Adding TLS 1.3 to the list of supported protocols in `ServicePointManager.SecurityProtocol` had no effect at all, presumably that's because TLS 1.3 is disabled by default in Windows 10.
* When I [enable TLS 1.3](https://stackoverflow.com/questions/56072561/how-to-enable-tls-1-3-in-windows-10) in the registry, .NET indeed starts to prefer TLS 1.3 according to my Wireshark traces.

I haven't done extensive tests, but what I've seen so far was inconsistent:
* With Endpoint Verification enabled (meaning IAP Desktop uses mTLS for most endpoints), all mTLS handshakes failed.
* With Endpoint Verification disabled, TLS worked (for a few tests) on a Windows 10 1909 machine, but failed on a 2004 machine.

IAP Desktop uses the .NET `HttpClient`, which in turn uses WinHTTP and SChannel under the hood. And according to [this table](https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-), TLS 1.3 is still _not supported_ (but available as _experimental_) on Windows 10 and below. That might explain some of the spotty results.

So I'm not sure if it's possible to implement this feature at this point. `gcloud` uses an entirely different HTTP stack, so it's not subject to the same (but other) limitations.

Is TLS 1.3 support a nice to have feature for you, or are there any compliance reasons to use TLS 1.3?

**Comment by vit4ever** [comment]
Both :) Nice to have and (future) compliance. In the end it is the most current and most secure version of TLS. It is hard to argue for TLS 1.2 if TLS 1.3 is available and supported. I was not aware that older versions of Windows 10 lack support for TLS 1.3. tbh  I tested IAP-desktop on a Windows Insider version so this might be the reason for the differences. However, both Windows 11 and Windows Server 2022 are probably going to be released in the next months.  And from what I read TLS 1.3 should be supported and enabled by default. Would it be possible to make the TLS version a configurable option, so people sticking to older versions of Windows still can use TLS 1.2 while people on the upcoming versions can use TLS 1.3?

**Comment by jpassing** [comment]
Yeah, I also would have expected TLS 1.3 support to be better by now... I haven't been able to test Windows 11 yet, but assuming TLS 1.3 works fine on Windows 11 and Server 2022 (as the documentation suggests), we could:

* enable TLS 1.3 by default on Windows 11 and Server 2022
* use TLS 1.2 on older versions

I'm hesitating to make the TLS version configurable because it might cause IAP Desktop to not even start properly anymore -- which then makes it difficult for a user to revert their configuration change. So it seems safer to me to detect the OS version and adapt settings automatically.

**Comment by jpassing** [comment]
The change is now available in [release 2.21](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.21.681).
