### ISSUE TITLE
Not able to SSH FIPS enabled RHEL8 VM with RSA key

### ISSUE THREAD

**Issue by saeedgenmills** [GoogleCloudPlatform/iap-desktop#567]
Getting error while connect FIPS enabled RHE 8 VMs from IAP Desktop. How can I use ECDSA key in IAP desktop ?

TIMESTAMP sshd[PID]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]

**Comment by jpassing** [comment]
Yes, this is currently a known issue: IAP Desktop uses `rsa-ssh`, which isn't supported by RHEL in FIPS mode since it relies on SHA-1.

I've been wanting to add `rsa-sha2-256` support, which would solve this issue. But this has been delayed because [libssh2 isn't ready yet](https://github.com/libssh2/libssh2/issues/536). I hope that'll be resolved soon.

Extending IAP Desktop to support `ecdsa-sha2-nistp256` in addition/as an alternative to `ssh-rsa` would be an option too. But managing a second key adds complexity, so I'm not too excited about this option. But if the libssh2 PR takes much longer, maybe it's the way to go.

**Comment by jpassing** [comment]
[Version 2.23.722](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.23.722) now lets you witch from RSA to ECDSA for public key authentication. This should enable you to connect to FIPS-compliant VMs.

Thanks you for reporting this issue.
