### ISSUE TITLE
Allow multiple full-screen sessions for RDP

### ISSUE THREAD

**Issue by AOCGIT** [GoogleCloudPlatform/iap-desktop#574]
Like Many Admins and Users, We use RDP and this is to be a capable replacement for RDP. However, It lacks any ability to have multiple "RDP Windows" open to different VMs in Full Screen.

Example. 
Users has 4 Monitors. User wants 1 Session Full Screen Per Monitor. Each Screen Connecting hosting its own Full Screen Connection to a different Server. 1 Server Connection per Monitor in Full Screen. This is a Simple and Easy task for RDP.

However this does not appear possible.

**Comment by jpassing** [comment]
The next version will let you to float/dock RDP sessions (#575) so that you can use multiple sessions in parallel and arrange them across multiple monitors. Still, only one of the sessions can be full-screen at a time. Having more than one session in full-screen  mode (in a single process) currently doesn't seem to be supported by the RDP control.
