### ISSUE TITLE
Allow detaching windows

### ISSUE THREAD

**Issue by AOCGIT** [GoogleCloudPlatform/iap-desktop#575]
Currently, there is Zero ability to Float Windows outside of IAP Desktop. Such as you can with Chrome Browser. All "Connections" to the VM are forced inside the App on the Right in Very Tiny Windows.

For 99% of users, we will all have multiple display monitors and require the ability to have windows assigned per monitor. We are Not asking to SPAN a VM's image across multiple windows or monitors! We are saying we want to pull and drag a window/connection to a VM and move that displayed window to its own dedicated Monitor/Screen and make it full screen.  3 Monitors = 3 separate windows/vms each full screen jsut like in RDP. 

Alternatively we have considered testing openening up 3 sessions of IAP Desktop side by side by side to accomplish this same very basic task, but to minimal avail.

**Comment by jpassing** [comment]
The app currently doesn't allow detaching windows because of some difficulties I encountered with the Windows RDP control: Detaching a window requires the RDP control to be re-parented and in my previous experiments, that caused the control to crash. So to play it safe, I disabled the feature. 

There might be a workaround though, I'll have to take a closer look again.
