### ISSUE TITLE
Enhancement request: allow color customization for terminal text

### ISSUE THREAD

**Issue by rmatte** [GoogleCloudPlatform/iap-desktop#713]
Allow color customization for the text in terminal sessions with a way to export/import themes (and possibly include some default color themes).  Also allow for the full xterm color set (currently seems to possibly be limited to 256?).

**Comment by jpassing** [comment]
Support for custom foreground/background colors is on the roadmap. It probably won't make it into the upcoming version (2.29), but the one after that (2.30).

**Comment by rmatte** [comment]
Awesome, thank you.

**Comment by rmatte** [comment]
Just to add to this, the ability to customize the background and foreground are great options to have, however I find the default colors being used for other stuff (blues, greens, etc...) are a bit dark in this.  I much prefer the color scheme being used by the google cloud web ssh client.  If you could adjust these to be more like that it would be easier on the eyes (basically make the colors a bit less harsh, more pastel).

**Comment by jpassing** [comment]
I agree, a dark gray background like the in-browser SSH client uses would be a better default.

**Comment by jpassing** [comment]
[IAP Desktop 2.30](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.30.878) now lets you customize foreground and background colors:

![image](https://user-images.githubusercontent.com/5724941/183796017-334d0c58-d930-40c7-b557-589a2e5b5243.png)

The default background is now a dark gray instead of black.

Thanks again for suggesting this feature.
