### ISSUE TITLE
Authorization failure

### ISSUE THREAD

**Issue by Joachim-Gourdon** [GoogleCloudPlatform/iap-desktop#734]
Dear,

When I log in IAP desktop I have the following message "Authorization failed because you have denied access to required resources. Sign is again and make sure to grant access to all requested resources."

What I don't understand, is that if I use the command line to access my GCE instances in RDP (using the command `gcloud compute start-iap-tunnel INSTANCE_NAME 3389 --local-host-port=localhost:LOCAL_PORT --zone=ZONE`) or in SSH (using the command `gcloud compute ssh INSTANCE_NAME`) it works.

Could you please advise.

Regards

Joachim

**Comment by jpassing** [comment]
When you signed in, you should have seen a consent screen like this:
![image](https://user-images.githubusercontent.com/5724941/180669056-c1402d58-dfe0-499d-a35e-599037937f25.png)

You must check that box to allow IAP Desktop to access cloud resources (and create IAP tunnels) on your behalf. If you don't, IAP Desktop shows this error message:

![image](https://user-images.githubusercontent.com/5724941/180670417-04a549a1-f11e-441c-8a23-eb0477a74a08.png)


For `gcloud`, the same mechanism applies -- with one difference: Because  `gcloud` is considered a first-party Google app, there's no check box and the scope is granted by default:


![image](https://user-images.githubusercontent.com/5724941/180670466-a42803c8-8cf0-4186-a269-7baf429f1447.png)

Does this answer your question?

**Comment by Joachim-Gourdon** [comment]
Thank you, it works.
