### ISSUE TITLE
SFTP - Illegal characters in path

### ISSUE THREAD

**Issue by dinesh1844** [GoogleCloudPlatform/iap-desktop#828]
Thanks for including the download feature. I am able to download most of the files successfully but when i navigate to a particular path getting the below error.

![tmp_bbb9ddf4-f8d1-425a-928a-6ae371301d63](https://user-images.githubusercontent.com/81134595/199875702-ec74731b-7681-4f05-82b0-d243ebba82d0.png)

**Comment by jpassing** [comment]
I guess one of the files in the directory has a name that's valid by POSIX standards, but considered invalid by Windows... and that causes the icon lookup to fail. 

Thanks for reporting this bug -- I'll look into this.

**Comment by jpassing** [comment]
This is now fixed and available in [release 2.34.988](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.34.988): If you download a file with a non-Win32-compliant filename, IAP Desktop will "escape" the filename so that it becomes Win32-compliant. For example, a file `dot.txt.` is downloaded as `dot.txt._`, or `COM1` is downloaded as `_COM1`.

Thanks again for reporting this issue!
