### ISSUE TITLE
Browser integration: add Password parameter

### ISSUE THREAD

**Issue by JackSlateur** [GoogleCloudPlatform/iap-desktop#872]
Hello,
Whilst checking out this [wiki page](https://github.com/GoogleCloudPlatform/iap-desktop/wiki/Browser-Integration), we noticed that there is no way to pass the password to the user via URL

We are using dedicated instances that are built on the fly when someone needs it
Users cannot generate credentials and must use a preinstalled account (preconfigured with all the required parts)

Could you add a parameter `Password` for this purpose ?
If that is not possible for some reason, maybe `CredentialGenerationBehavior` could be improved to ask the user for the password, as it is possible when IAP desktop is ran manually:
![image](https://user-images.githubusercontent.com/1293082/220154026-250501af-3772-4406-b233-db38bfba1799.png)

Best regards,

**Comment by jpassing** [comment]
That's right, IAP Desktop currently doesn't let you to specify a password in the URL. The concern here is that users might bookmark URLs, use them to create Windows shortcuts, or email them around... so it's difficult to keep passwords safe when they're embedded in an URL.

> If that is not possible for some reason, maybe CredentialGenerationBehavior could be improved to ask the user for the password, as it is possible when IAP desktop is ran manually

Have you tried `CredentialGenerationBehavior=2`(_do not allow generating new credentials_)? When I use the query string `?Username=test&Domain=.&CredentialGenerationBehavior=2` and don't have any persisted credentials, then this popup shows:

![image](https://user-images.githubusercontent.com/5724941/220216929-1a9c2eeb-f9a9-4b86-b22d-d1c62af8e819.png)

Is this what you had in mind?

**Comment by JackSlateur** [comment]
Hello,

Partly, yes
Using this url:
`iap-rdp:///${project}/europe-west9-a/lab-abr12364789?Username=admin&Domain=.&CredentialGenerationBehavior=2`
I got this:
![image](https://user-images.githubusercontent.com/1293082/220291820-a87c6645-1b7a-45fb-9755-1776429d337f.png)

There is one minor issue: domain is still set

And one major issue: password cannot be set, so user must fill it in for each connection

**Comment by jpassing** [comment]
> There is one minor issue: domain is still set

Instead of `?Username=admin&Domain=.&CredentialGenerationBehavior=2`, could you try:

* `?Username=.\admin&CredentialGenerationBehavior=2`  (`.\` prefix in username, leave out `Domain`) _or_
* `?Username=lab-abr12364789\admin&CredentialGenerationBehavior=2` (explicitly use target machine name as prefix in username, leave out `Domain`)

Both options should have the same effect.


> And one major issue: password cannot be set, so user must fill it in for each connection

Right. It's interesting that you get the error message _Your system administrator does not allow the use of saved credentials_ though. If you connect to a VM from within Project Explorer and have saved credentials, are you being logged in automatically? Or do you get the same error despite having saved credentials?

The reason I ask: Suppose we changed IAP Desktop so that you can pass a password via URL. If you have a group policy set up that disallows saved RDP credentials, then it still wouldn't work because the password would be considered a _saved credential_.

**Comment by JackSlateur** [comment]
Both syntaxes gave me the same results

If I connect to the VM from within the project manager with saved credentials:
![image](https://user-images.githubusercontent.com/1293082/220531699-64d98387-9ae9-448f-b007-63b2a4cadc96.png)

Then I can connect without any password asked

From there, I can connect via this url (note that `Username` must not be passed):
`iap-rdp:///${project}/europe-west9-a/lab-abr-3456789`

**Comment by jpassing** [comment]
Ok, thanks for verifying.

What do you think of the following idea:

* Instead of including the password in the URL, you include a "callback URL", for ex: `iap-rdp:///${project}/europe-west9-a/lab-abr-3456789?Username=bob&PasswordCallback=https://portal.example.com/get-password?parameters=AAAA...`.
* IAP Desktop, when launched using such an URL, makes an HTTP request to the URL to retrieve the password. 

You could then use techniques such as URL signing to ensure that the embedded URL is only valid for, say, 1 minute. That would be enough for users to launch IAP Desktop and automatically connect -- but short enough that URLs that are bookmarked or emailed around don't [become too much of a risk](https://www.rfc-editor.org/rfc/rfc3986#section-7.5).

Another option would be to add a `Password` parameter along with a new configuration option "Allow URLs to contain credentials" and let this option default to off.

I'd prefer the first option, but would ok with the second. Wdyt?

**Comment by JackSlateur** [comment]
Hello,

The URL solution would work, we could easily setup a cloud function linked to a memorystore or something

**Comment by jpassing** [comment]
Great. I'm not sure if I can still fit that into the upcoming 2.35 release as that's mostly done already. But the one after should work.

**Comment by jpassing** [comment]
I implemented the feature and have attached a (signed) pre-release build. It would be great if you could give that a try:

[IapDesktop-2.35.1055-x86-Release.msi.zip](https://github.com/GoogleCloudPlatform/iap-desktop/files/11084246/IapDesktop-2.35.1055-x86-Release.msi.zip)

This build now supports an additional [URL parameter](https://github.com/GoogleCloudPlatform/iap-desktop/wiki/Browser-Integration) named `CredentialCallbackUrl`. When this parameter is present, IAP Desktop does the following:

* It ignores the `Username`, `Domain`, and `RdpCredentialGenerationBehavior` parameters
* It performs a HTTP GET request to the URL, and expects a result in the following format:

  ```
  {
   Domain: ".",
   User: "user",
   Password: "password"
  }
  ```

  It then uses these credentials to perform the RDP login.

As discussed previously, the callback endpoint should ensure that a URL can only be queried once, or can only be used within a short period of time.

Let me know if this works as intended, or if you notice anything else that doesn't look right to you.

**Comment by JackSlateur** [comment]
Hello,
It works as expected !
I've tested both simple url (`https://fqdn/resource`) as well as url with one and many parameters
The later works by url encoding: `https://fqdn/resource?param1=value1%26param2=value2`
System proxy settings are also used

This perfectly suits our need, thank you

**Comment by jpassing** [comment]
Great, happy to hear that it works as expected.

I'll keep this issue open until the release is out, which I expect to happen around end of April. Then I'll also update the documentation page.

**Comment by jpassing** [comment]
[Release 2.36](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.36.1101) is now available I also updated [the documentation](https://github.com/GoogleCloudPlatform/iap-desktop/wiki/Browser-Integration).

Thanks again for suggesting this feature.
